# Rubocop,  we're buddies and all,  but we're going to have to disagree on the following -

AllCops:
  Exclude:
    - foodcritic/**/*
    - vendor/**/*

Style/LineLength:
  Max: 200

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/WordArray:
  MinSize: 5
